

%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql/${POSTGRES_DB}
%prod.quarkus.datasource.username=${POSTGRES_USER}
%prod.quarkus.datasource.password=${POSTGRES_PASSWORD}

%dev.quarkus.hibernate-orm.log.sql=true

# OpenTelemetry Tracing for Service Mesh 
quarkus.application.name=tam-your-tech
# OTel metrics off by default
quarkus.otel.metrics.enabled=true


# OTLP Traces &amp; Metrics Exporters 
quarkus.otel.exporter.otlp.traces.protocol=http/protobuf
quarkus.otel.exporter.otlp.traces.endpoint=http://cluster-collector-collector.product-catalog.svc.cluster.local:4318/v1/traces 

quarkus.otel.exporter.otlp.metrics.protocol=grpc
quarkus.otel.exporter.otlp.metrics.endpoint=http://cluster-collector-collector.product-catalog.svc.cluster.local:4317/v1/metrics


# OTel logs off by default
quarkus.otel.logs.enabled=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
# Don't run the Grafana LGTM dev service during tests
%test.quarkus.observability.enabled=false
%dev.quarkus.otel.exporter.otlp.enabled=false 
%test.quarkus.otel.exporter.otlp.enabled=false


