

%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql/${POSTGRES_DB}
%prod.quarkus.datasource.username=${POSTGRES_USER}
%prod.quarkus.datasource.password=${POSTGRES_PASSWORD}

%dev.quarkus.hibernate-orm.log.sql=true

# OpenTelemetry Tracing for Service Mesh 
quarkus.application.name=tam-your-tech
# OTel metrics off by default
quarkus.otel.metrics.enabled=true
quarkus.otel.suppress-nested-automatic-spans=true
quarkus.otel.exporter.otlp.traces.protocol=http/protobuf
quarkus.otel.exporter.otlp.endpoint=http://cluster-collector-collector.product-catalog.svc.cluster.local:4318 
quarkus.otel.exporter.otlp.traces.endpoint=http://cluster-collector-collector.product-catalog.svc.cluster.local:4318/v1/traces
quarkus.otel.exporter.otlp.metrics.enabled=false
# OTel logs off by default
quarkus.otel.logs.enabled=true
quarkus.otel.exporter.otlp.traces.headers=Authorization=Bearer my_secret
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
# Don't run the Grafana LGTM dev service during tests
%test.quarkus.observability.enabled=false

# Micrometer Metrics 
quarkus.micrometer.enabled=true 
quarkus.micrometer.export.prometheus.enabled=true 
quarkus.micrometer.binder.jvm=true 
quarkus.micrometer.binder.http-server.enabled=true 

