quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=techlab
quarkus.datasource.password=techlab
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql-vm-svc.techlab-vms.svc.cluster.local:5432/techlab
quarkus.hibernate-orm.database.generation=update
quarkus.mongodb.connection-string=
