quarkus.mongodb.connection-string=mongodb://techlab:techlab@mongodb-vm-svc.techlab-vms.svc.cluster.local:27017/techlab
quarkus.datasource.jdbc=false
quarkus.hibernate-orm.enabled=false
app.repository.type=mongodb
