quarkus.application.name=product-catalog
quarkus.http.port=8080

# Redis
quarkus.redis.hosts=redis://:techlab@redis-svc.techlab-vms.svc.cluster.local:6379

# Repository type (jpa or mongodb — overridden per profile)
app.repository.type=jpa

# OpenTelemetry
quarkus.otel.exporter.otlp.endpoint=http://otel-collector.techlab-app.svc.cluster.local:4317
quarkus.otel.service.name=product-catalog

# Health
quarkus.smallrye-health.root-path=/q/health
